language: r
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 2.2
latex: false

before_install:
  - mkdir ~/.R
  - cp Makevars ~/.R
  - npm install netlify-cli -g
  - curl -fLo /tmp/tinytex.tar.gz https://travis-bin.yihui.name/tinytex.tar.gz
  - tar xzf /tmp/tinytex.tar.gz -C /$HOME
  - export PATH=/$HOME/.TinyTeX/bin/x86_64-linux:$PATH

script:
  - Rscript -e 'bookdown::render_book("index.Rmd",output_format = "all")'

deploy:
  provider: script
  script: netlify deploy -t $NETLIFY_PAT
  skip_cleanup: true
