---
title: Contributing
layout: default
---

# Contributing

This book has been developed in the open, and it wouldn't be nearly as good 
without your contributions. There are a number of ways you can help make the
book even better:

* If you don't understand something, please 
  [let me know](mailto:h.wickham@gmail.com). Your feedback on what is confusing
  or hard to understand is valuable.

* If you spot a typo, feel free to edit the underlying page and send a pull 
  request. If you've never done this before, the process is very easy: 
  
    * Click the edit this page on the sidebar.
  
    * Make the changes using github's in-page editor (fixing typos is
      perfectly adequate).
      
    * Include a brief description of your changes in the area below the
      editor, then propose the file change. If you make significant changes,
      include the phrase "I assign the copyright of this contribution to
      Hadley Wickham" - I need this so I can publish the printed book.
    
    * Create a pull request.
