---
layout: default
title: Welcome
---

# Welcome

This is the in-progress book site for __"Advanced R development"__. The book is designed primarily for R users who want to improve their programming skills and understanding of the language.  It should also be useful for programmers coming to R from other languages, as it explains some of R's quirks and shows how some parts that seem horrible do have a positive side.

It will eventually be published as a real book in Chapman and Hall's [R series](http://www.crcpress.com/browse/series/crctherser).  The final version of the book is due in December 2013, so it should be available in early 2014. Thanks to the publisher, the wiki will continue to be freely available after the book is published.

## Advanced R programming

Learn all about how the R language works and how you can use it to solve real problems. The book is broken down into the following chapters (which you can also access from the drop-down menus at the top-right):

<ul class="toc">
  {% include programming-nav.html %}
</ul>

## Package development

Packages are the fundamental units of reproducible R code. They include reusable R functions, the documentation that describes how to use them, and sample data. In this section you'll learn how to turn your code into packages that others can easily download and use. 

Writing a package can seem overwhelming at first. So start with the basics and improve it over time. It doesn't matter if your first version isn't perfect as long as the next version is better.
 
<ul class="toc">
  {% include package-nav.html %}
</ul>
