# (PART) Object oriented Programming {-}

# OO field guide {#oo}

This chapter is a field guide for recognising and working with R's objects in the wild. R has three object oriented systems (plus the base types), so it can be a bit intimidating. The goal of this guide is not to make you an expert in all four systems, but to help you identify which system you're working with and to help you use it effectively. \index{object-oriented programming}

Central to any object-oriented system are the concepts of class and method. A __class__ defines the behaviour of __objects__ by describing their attributes and their relationship to other classes. The class is also used when selecting __methods__, functions that behave differently depending on the class of their input. Classes are usually organised in a hierarchy: if a method does not exist for a child, then the parent's method is used instead; the child __inherits__ behaviour from the parent.

R's three OO systems differ in how classes and methods are defined:

* __S3__ implements a style of OO programming called generic-function OO. 
  This is different from most programming languages, like Java, C++, and C#,
  which implement message-passing OO. With message-passing, messages (methods)
  are sent to objects and the object determines which function to call.
  Typically, this object has a special appearance in the method call, usually
  appearing before the name of the method/message: e.g., 
  `canvas.drawRect("blue")`. S3 is different. While computations are still
  carried out via methods, a special type of function called a 
  __generic function__ decides which method to call, e.g., 
  `drawRect(canvas, "blue")`. S3 is a very casual system. It has no 
  formal definition of classes.

* __S4__ works similarly to S3, but is more formal. There are two major
  differences to S3. S4 has formal class definitions, which describe the
  representation and inheritance for each class, and has special helper
  functions for defining generics and methods. S4 also has multiple dispatch,
  which means that generic functions can pick methods based on the class of 
  any number of arguments, not just one.

* __Reference classes__, called RC for short, are quite different from S3 
  and S4. RC implements message-passing OO, so methods belong to classes, 
  not functions. `$` is used to separate objects and methods, so method calls
  look like `canvas$drawRect("blue")`. RC objects are also mutable: they don't
  use R's usual copy-on-modify semantics, but are modified in place. This 
  makes them harder to reason about, but allows them to solve problems that 
  are difficult to solve with S3 or S4.

There's also one other system that's not quite OO, but it's important to mention here:

* __base types__, the internal C-level types that underlie the other OO 
  systems. Base types are mostly manipulated using C code, but they're 
  important to know about because they provide the building blocks for the 
  other OO systems.

The following chapters describe each system in turn, starting with base types. You'll learn how to recognise the OO system that an object belongs to, how method dispatch works, and how to create new objects, classes, generics, and methods for that system. The chapter concludes with a few remarks on when to use each system.

## Why OO?

The primary use of OO programming in R is for print, summary and plot methods. These methods allow us to have one generic function, e.g. `print()`, that displays the object differently depending on its type: printing a linear model is very different to printing a data frame.


## Identifying 

* base type
* S3
* S4
* R6
* RC


### Recognising objects and methods

You can recognise RC objects because they are S4 objects (`isS4(x)`) that inherit from "refClass" (`is(x, "refClass")`). `pryr::otype()` will return "RC".  RC methods are also S4 objects, with class `refMethodDef`.

