---
title: Profiling and benchmarking
layout: default
---

```{r, echo = FALSE}
options(digits = 3)
```

# Profiling and performance optimisation {#profiling}

> "We should forget about small efficiencies, say about 97% of the time:
> premature optimization is the root of all evil" --- Donald Knuth.

Your code should be correct, maintainable and fast. Notice that speed comes last - if your function is incorrect or unmaintainable (i.e. will eventually become incorrect) it doesn't matter if it's fast. As computers get faster and R is optimised, your code will get faster all by itself. Your code is never going to automatically become correct or elegant if it is not already.

That said, sometimes there are times where you need to make your code faster: spending several hours of your day might save days of computing time for others. The aim of this chapter is to give you the skills to figure out why your code is slow, what you can do to improve it, and ensure that you don't accidentally make it slow again in the future.  You may already be familiar with `system.time`, which tells you how long a block of code takes to run. This is a useful building block, but is a crude tool.

Making fast code is a four part process:

1. Profiling helps you discover parts of your code are taking up the most time

2. Microbenchmarking lets you experiment with small parts of your code to find faster approaches.

3. Timing helps you check that the micro-optimisations have a macro effect, and helps experiment with larger changes (like totally rethinking your approach)

4. A performance testing tool makes sure your code stays fast in the future  (e.g. [Vbench](http://wesmckinney.com/blog/?p=373))

Along the way, you'll also learn about the most common causes of poor performance in R, and how to address them. Sometimes there's no way to improve performance within R, and you'll need to use C++, the topic of [Rcpp](#rcpp).

Having a good test suite is important when tuning the performance of your code: you don't want to make your code fast at the expense of making it incorrect. We won't discuss testing any further in this chapter, but we strongly recommend having a good set of test cases written before you begin optimisation.

Good exploration from Winston: http://rpubs.com/wch/3797

Find out what is slow. Then make it fast.

[Mature optimisation](http://carlos.bueno.org/optimization/mature-optimization.pdf) (PDF)


## Performance profiling

R provides a built in tool for profiling: `Rprof`. When active, this records the current call stack to disk very `interval` seconds. This provides a fine grained report showing how long each function takes. The function `summaryRprof` provides a way to turn this list of call stacks into useful information. But I don't think it's terribly useful, because it makes it hard to see the entire structure of the program at once. Instead, we'll use the `profr` package, which turns the call stack into a data.frame that is easier to manipulate and visualise.

Example showing how to use profr.

Sample pictures.

## Timing

## Performance testing



## Caching

`readRDS`, `saveRDS`, `load`, `save`

Caching packages

### Memoisation

A special case of caching is memoisation.

## Byte code compilation

R 2.13 introduced a new byte code compiler which can increase the speed of certain types of code 4-5 fold. This improvement is likely to get better in the future as the compiler implements more optimisations - this is an active area of research.

Using the compiler is an easy way to get speed ups - it's easy to use, and if it doesn't work well for your function, then you haven't invested a lot of time in it, and so you haven't lost much.

## Other people's code

One of the easiest ways to speed up your code is to find someone who's already done it! Good idea to search for CRAN packages.

    RppGSL, RcppEigen, RcppArmadillo

Stackoverflow can be a useful place to ask.

### Important vectorised functions

Not all base functions are fast, but many are. And if you can find the one that best matches your problem you may get big improvements

    cumsum, diff
    rowSums, colSums, rowMeans, colMeans
    rle
    match
    duplicated

Read the source code - implementation in C is usually correlated with high performance.

## Rewrite in a lower-level language

C, C++ and Fortran are easy. C++ easiest, recommended, and described in the following chapter.
