
## Practicalities

### Method families

* When implementing a vector class, you should implement these methods: `length`, `[`, `[<-`, `[[`, `[[<-`, `c`.  (If `[` is implemented `rev`, `head`, and `tail` should all work).  Also need to implement `as.data.frame`

* When implementing anything mathematical, implement `Ops`, `Math` and `Summary`.

* When implementing a matrix/array class, you should implement these methods: `dim` (gets you nrow and ncol), `t`, `dimnames` (gets you rownames and colnames), `dimnames<-` (gets you colnames<-, rownames<-), `cbind`, `rbind`.

* If you're implementing more complicated `print()` methods, it's a better idea to implement `format()` methods that return a string, and then implement `print.class <- function(x, ...) cat(format(x, ...), "\n"`. This makes for methods that are much easier to compose, because the side-effects are isolated to a single place.

* model fitting

This is a quick and dirty way to create data frames. It does little checking (i.e. all columns need to have unique names, and be the same length), but assuming you give it valid input it gives you a valid data frame class. You'll need this if you want to create your own vector class because you need a `as.data.frame` method that returns a data frame.

```{r}
new_data_frame <- function(x, row_names = NULL) {
  stopifnot(is.list(x))

  if (is.null(row_names)) {
    n <- if (length(x) == 0) 0 else length(x[[1]])
    row_names <- .set_row_names(n)
  }


  structure(x,
    class = "data.frame",
    row.names = row_names
  )
}
```



### Packaging

* Beware class clashes across packages. If there's any chance of confusion
  give your classes a common prefix.

* If you define your own generics, make sure you document it from both a user
  perspective and the perspective of a devloper. Be clear about the contract
  that the generic provides.

* Don't export methods; use `S3method()` so they can be found.
  This registers the method is a special environment that is accessible to
  `UseMethod()` but not directly via `::`. This is good practice.

