### Trade space for time

A very general optimisation technique is to trade space for time by caching results. Instead of computing repeatedly, you compute once and then look up again in the future. A special case of caching is memoisation.

http://en.wikipedia.org/wiki/Dynamic_programming: "The idea behind dynamic programming is quite simple. In general, to solve a given problem, we need to solve different parts of the problem (subproblems), then combine the solutions of the subproblems to reach an overall solution. Often when using a more naive method, many of the subproblems are generated and solved many times. The dynamic programming approach seeks to solve each subproblem only once, thus reducing the number of computations: once the solution to a given subproblem has been computed, it is stored or "memo-ized": the next time the same solution is needed, it is simply looked up. This approach is especially useful when the number of repeating subproblems grows exponentially as a function of the size of the input."

In R, you should be most familiar with `readRDS()` and `saveRDS()`. They allow you to save and load individual R object to disk. Use them in preference to `save()` and `load()` which work with complete workspaces. Depending on the speed of your disk, how much disk space you have free and the speed of your CPU, it may be worth setting `compress = FALSE`. You can make richer trade-offs between disk space and compression time by doing the compression yourself: see the `?saveRDS` examples for details.

Caching packages: memoise, hash, http://cran.r-project.org/web/packages/cacher/index.html, http://cran.r-project.org/web/packages/R.cache/index.html
